FOGL-1654: C++ North plugins have incorrect API
foglamp/FogLAMP pull request #1061
Opened 2018-08-31 10:04 UTC by pintomax

C++ North plugins have incorrect API

With this change the “plugin_init” method takes as parameter a ConfigCategory object instead of a JSON string map configuration. 

The "PI_Server" north plugin only has new method “plugin_extra_config”.

When this method is called it returns a JSON with additional categories to create/update.
Those category items (created/updated and fetched) are passed back to plugin via “plugin_init” as new items with this name format:
CATEGORY_NAME . INTEM_NAME, i.e.
OMF_TYPES.type-id

The  "PI_Server" plugins now looks for string typesId = configData->getValue("OMF_TYPES.type-id"); 
NOTE: if the method “plugin_extra_config” doesn’t exist and it's called, an empty string is returned.

 
get_plugin_info utility updated with “plugin_extra_config”:

plugins/utils/get_plugin_info plugins/north/PI_Server/libPI_Server.so.1 plugin_extra_config | jq

```
{
  "name": "Additional configuration",
  "description": "Additional configuration categories to pass to plugin_init",
  "categories": {
    "OMF_TYPES": {
      "type-id": {
        "description": "Identify sensor and measurement types",
        "type": "integer",
        "default": "0001"
      }
    }
  }
}
```

2018-09-03 06:30 UTC, AmandeepArora requested changes

2018-09-03 06:52 UTC, pintomax commented on C/plugins/north/PI_Server/plugin.cpp
> +	string* handle = new string(string(PLUGIN_NAME) + " initialised");
This PI_Server plugin, the former OMF one, was the first C++ north plugin ever written.
I'll follow your suggestions, thanks.

2018-09-03 07:07 UTC, pintomax commented on C/plugins/north/PI_Server/plugin.cpp
> +#define OMF_PLUGIN_DESC "\"plugin\": {\"description\": \"OMF North C Plugin\", " \
Yes, working on it

2018-09-03 07:28 UTC, pintomax commented on C/plugins/north/http-north/plugin.cpp
> -						string(PLUGIN_DEFAULT_CONFIG)
Fixed

2018-09-03 07:28 UTC, pintomax commented on C/plugins/north/ThingSpeak/plugin.cpp
> -						string(PLUGIN_DEFAULT_CONFIG)
Fixed

2018-09-03 08:04 UTC, pintomax commented on C/plugins/north/PI_Server/plugin.cpp
> +	string* handle = new string(string(PLUGIN_NAME) + " initialised");
Fixed

2018-09-03 08:11 UTC, AmandeepArora approved these changes

2018-09-03 10:43 UTC, MarkRiddoch requested changes

2018-09-03 10:43 UTC, MarkRiddoch commented on C/tasks/north/sending_process/include/north_plugin.h
> +		std::string&		(*pluginExtraConfig)();
Not happy with this extension to the API

2018-09-03 13:35 UTC, MarkRiddoch commented
Having discussed this with Stefano it appears that it is feasible to make the handling of the increment automatic and not have to confuse the user with this parameter. All that remains is to define the way for the plugin to persist data between executions without using the configuration manager. The Python codes gets a handle to the storage layer, via an incorrect use of the plugin handle. Although not right it might signify that creating a legitimate mechanism for the plugin to get an handle on the storage layer is the best solution.

2018-10-03 09:38 UTC, closed without merging

2018-10-03 09:39 UTC, pintomax commented
Closing PR. Another will be created for North C++ API  fixes