Python lab script
foglamp/FogLAMP pull request #1717
Opened 2019-09-30 07:44 UTC by YashTatkondawar

2019-09-30 16:06 UTC, praveen-garg requested changes

2019-09-30 16:06 UTC, praveen-garg commented on tests/system/python/packages/test_fog.py
> +
Let's rename it to test_lab.

2019-09-30 16:06 UTC, praveen-garg commented on tests/system/python/packages/test_fog.py
> +class TestToggledEvent:
move TestToggledEvent (1) test and TestPositiveNegativeSineNotification (2) under TestEventEngine itself. and also add assertions as required.

2019-09-30 16:07 UTC, praveen-garg commented
@YashTatkondawar  Closing this pull request, as it is coming from the forked repo. Please open a new PR

2019-09-30 16:07 UTC, closed without merging

2019-10-01 05:30 UTC, YashTatkondawar commented
Okay sir once I update the above mentioned changes I will open a new PR.