FOGL-3718 Added API endpoint to remove plugin from FogLAMP
foglamp/FogLAMP pull request #1834
Opened 2020-02-12 11:27 UTC by rajeshkumar426

Signed-off-by: rajeshkumar426 <rajeshkumar426@outlook.com>

2020-02-12 11:38 UTC, MarkRiddoch requested changes

2020-02-12 11:38 UTC, MarkRiddoch commented on python/foglamp/services/core/api/plugins/remove.py
> +        curl -X DELETE http://host-ip:port/foglamp/plugins/south/sinusoid/remove
There is no need to have the /remove on the end of the URL, this is a DELETE operation

2020-02-13 08:21 UTC, pintomax requested changes

2020-02-13 08:21 UTC, pintomax commented on python/foglamp/services/core/routes.py
> +    app.router.add_route('DELETE', '/foglamp/plugins/{type}/{name}/remove', remove.plugin_delete)
We don't need "/remove" at the end of URL

2020-05-16 17:16 UTC, closed without merging